development:
  mysql41: 9306
  morphology: stem_en
  morphology: stem_ru

test:
  mysql41: 9307

production:
  pid_file: /home/deployer/qna/shared/tmp/pids/searchd.pid
  morphology: stem_en
  morphology: stem_ru
